gen_config: Trap exit and echo if successful or not.
In the gen_config script trap the exit and echo out whether successful
or not. On more than one occasion a user has put forth CLs that appear
to have gotten past `lucicfg generate` but are failing before
`convert_proto_enums.py`. It seems that there is some failure path that
is not making it obvious that it failed. This will make it obvious.

BUG=None
TEST=locally breaking the script and observing output

Change-Id: Ib03d80815c104afe2b2839433a85095726b90b0e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/config/+/2313657
Reviewed-by: Sean McAllister <smcallis@google.com>
Commit-Queue: David Burger <dburger@chromium.org>
Tested-by: David Burger <dburger@chromium.org>

diff --git a/bin/gen_config b/bin/gen_config
--- a/bin/gen_config
+++ b/bin/gen_config
@@ -12,6 +12,16 @@
 # Exit if any command fails.
 set -e
 
+trap "summarize" EXIT
+
+function summarize() {
+  if [[ $? -eq 0 ]]; then
+    echo "Config generation complete."
+  else
+    echo "Config generation failed!!!" >&2
+  fi
+}
+
 function usage() {
   echo "Usage: $0 <config_file>" >&2
   echo "  where <config_file> is a program's or project's main" >&2
@@ -34,7 +44,7 @@ readonly config_dir="$(dirname "$(realpath -e "${file_path}")")"
 cd "${config_dir}"
 
 if ! config/generate.sh; then
-  echo 'blew up generating proto descriptors'
+  echo "blew up generating proto descriptors" >&2
   exit 1
 fi
 
