Check for LOAS credentials in create_partner_repo script.
BUG=None
TEST=None

Change-Id: I5d4cf0a0ed1e84a30a6afb8bcea2e14be93a07e7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/config/+/2202218
Reviewed-by: Andrew Lamb <andrewlamb@chromium.org>
Commit-Queue: David Burger <dburger@chromium.org>
Tested-by: David Burger <dburger@chromium.org>

diff --git a/sbin/create_partner_repo b/sbin/create_partner_repo
--- a/sbin/create_partner_repo
+++ b/sbin/create_partner_repo
@@ -344,6 +344,13 @@ run_command() {
 }
 
 
+if ! prodcertstatus; then
+  # Some of the commands require LOAS credentials. For example, without LOAS
+  # credentials, the gob-ctl to set readers on repos will fail.
+  echo "LOAS credentials missing. Please log in with prodaccess." >&2
+  exit 1
+fi
+
 while [[ "$1" != "" ]]; do
   case $1 in
     --program)
